apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip
spec:
  type: ClusterIP
  # ServerClusterIp is coupled to the selector (metadata) tags.
  # Which are entirely customizable.
  selector:
    folder: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379