apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'

    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'

    # Certificate config
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
        - multi-k8s.vandersangen.dev
      secretName: multi-k8s-vandersangen-dev
  rules:
    - host: multi-k8s.vandersangen.dev
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip
                port:
                  number: 5000

#    Boilerplate (untested yet) for multiple-domains in 1 ingress
#    - host: multi-k8s-other-domain.vandersangen.dev
#      http:
#        paths:
#          - path: /?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: client-cluster-ip
#                port:
#                  number: 3000
#          - path: /api/?(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: server-cluster-ip
#                port:
#                  number: 5000