apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip
spec:
  type: ClusterIP
  # ServerClusterIp is coupled to the selector (metadata) tags.
  # Which are entirely customizable.
  selector:
    folder: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000