apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      folder: postgres
  template:
    metadata:
      labels:
        folder: postgres
    spec:
      restartPolicy: Always
      # Assign PVC to Deployment pods. Comes from pvc.yaml in current folder
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            # For clarity; The POSTGRES_PASSWORD is given to the postgres image.
            # And it is retrieved from a k8s secret named secret-pgpassword
            # with a literal; PGPASSWORD
            # kubectl create secret generic secret-pgpassword --from-literal PGPASSWORD=<your-actual-password>
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-pgpassword
                  key: PGPASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pvc
              subPath: postgres
