apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  #  storageClassName: standard (Default online storage of current platform). Not needed to be specified.
  # Unless other is required (https://kubernetes.io/docs/concepts/storage/storage-classes/)
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
