apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pvc
spec:
  #  storageClassName: standard (Default coherent online storage. Not needed to be specified
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
