name: Deploy MultiK8s to GKE
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t larsvandersangen/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true larsvandersangen/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: '${{ vars.GKE_PROJECT_ID }}'

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: '${{vars.GKE_CLUSTER_NAME}}'
          location: '${{ vars.GKE_REGION }}'

      - name: Build Docker images
        run: |-
          docker build -t larsvandersangen/multi-client:latest -t larsvandersangen/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t larsvandersangen/multi-server:latest -t larsvandersangen/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t larsvandersangen/multi-worker:latest -t larsvandersangen/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push Docker images
        run: |-
          docker push larsvandersangen/multi-client:latest
          docker push larsvandersangen/multi-server:latest
          docker push larsvandersangen/multi-worker:latest
          
          docker push larsvandersangen/multi-client:${{ env.SHA }}
          docker push larsvandersangen/multi-server:${{ env.SHA }}
          docker push larsvandersangen/multi-worker:${{ env.SHA }}

      - name: Apply k8s files
        run: |-
          kubectl apply -f ./k8s/client/
          kubectl apply -f ./k8s/ingress/
          kubectl apply -f ./k8s/postgress/
          kubectl apply -f ./k8s/redis/
          kubectl apply -f ./k8s/server/
          kubectl apply -f ./k8s/worker/
          
          kubectl set image deployments/server-deployment server=larsvandersangen/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=larsvandersangen/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=larsvandersangen/multi-worker:${{ env.SHA }}